# Basic
title: 邓辉
subtitle: 不要惊慌
description: 记录个人生活感悟和学习心得的一个小空间，定期的复盘和反思。<br>回头看我人生中的各个点所连成的线。
# 头像里面的标题
avatarTitle: mylord
# 头像里面的描述
avatarDesc: 专注于视觉感知技术学习
url: "http://my-lord.cn"

# Comment
disqus_username: denghui
# disqus_username: http:\\www.my-lord.cn
#·comment:


# Social
social:
    weibo: 
    github: mylord.github
    # twitter: 
    mail: 904143076@qq.com

# 百度统计 
# 使用博客模板请去掉或者更换 id 
baidu:
    id: c63c3f73d45d69e4524c352af95e094e  

# Google Analytics
# 使用博客模板请去掉或者更换 id
# ga:
#     id: UA-84134159-3   
#     host: auto  


# 《----------------- 上面的信息修改成你自己的 ---------------------------》
#
#
#  _post/ 下的文章更换成你自己的文章
#  帮忙star一下，感谢~😆 地址： https://github.com/slowlythinking/slowlythinking.github.io
#
#
# 《--------------- 下面的信息可以自行选择是否修改 ------------------------》


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color:
# cover_color: clear
# cover_color: blue

# The blog button should not be removed.
blog_button:
    title: 博客

# Navigation buttons in the front page.s
nav:
    - {title: 主页, description: index, url: '/index'}  
    - {title: 列表, description: archive, url: '/archive'}   
    - {title: 标签, description: tags, url: '/tags'} 
    - {title: 关于, description: about, url: '/about'}      
    

# Pagination
#·gems: [jekyll-paginate,jekyll-sitemap]
gems: [jekyll-paginate]
paginate: 20
paginate_path: "page/:num/"

kramdown:
  hard_wrap: true # 将每个换行符都转换为 <br>，无需两个空格

theme: jekyll-theme-cayman